export const borrowManifest = (
  accountAddress,
  collateralResourceAddress,
  componentAddress,
  collateralAmount,
  borrowAmount
) => `
    CALL_METHOD
        Address("${accountAddress}")
        "withdraw"
        Address("${collateralResourceAddress}")
        Decimal("${collateralAmount}")
    ;
    TAKE_FROM_WORKTOP
        Address("${collateralResourceAddress}")
        Decimal("${collateralAmount}")
        Bucket("bucket1")
    ;
    CALL_METHOD
        Address("${componentAddress}")
        "borrow"
        Decimal("${borrowAmount}")
        Bucket("bucket1")
    ;
    CALL_METHOD
        Address("${accountAddress}")
        "try_deposit_batch_or_refund"
        Expression("ENTIRE_WORKTOP")
        Enum<0u8>()
    ;
`;
